# Generated by Django 5.1.15 on 2026-09-11 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='地区编码')),
                ('name', models.CharField(max_length=64, verbose_name='地区名称')),
            ],
            options={
                'verbose_name': '适用地区',
                'verbose_name_plural': '适用地区',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(verbose_name='总量是否完整（无未核算项）')),
                ('accounted_kg', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='已核算合计 kgCO2e')),
                ('unaccounted_count', models.PositiveIntegerField(default=0, verbose_name='未核算活动条数')),
                ('result_json', models.JSONField(default=dict, verbose_name='完整计算结果')),
                ('confirmed', models.BooleanField(default=False, verbose_name='是否已确认')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '核算报告',
                'verbose_name_plural': '核算报告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='单位编码')),
                ('name', models.CharField(max_length=32, verbose_name='单位名称')),
                ('dimension', models.CharField(choices=[('energy', '能量'), ('mass', '质量'), ('volume', '体积'), ('count', '件数')], max_length=16, verbose_name='量纲')),
                ('factor_to_base', models.DecimalField(decimal_places=10, max_digits=30, verbose_name='换算到基准单位的倍数')),
            ],
            options={
                'verbose_name': '计量单位',
                'verbose_name_plural': '计量单位',
                'ordering': ['dimension', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='因子编码')),
                ('version', models.CharField(max_length=16, verbose_name='版本')),
                ('name', models.CharField(max_length=128, verbose_name='因子名称')),
                ('activity_type', models.CharField(choices=[('electricity', '电力'), ('fuel', '燃料'), ('auxiliary', '辅料')], max_length=16, verbose_name='适用活动类型')),
                ('denominator_dimension', models.CharField(choices=[('energy', '能量'), ('mass', '质量'), ('volume', '体积'), ('count', '件数')], max_length=16, verbose_name='分母量纲')),
                ('value', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='因子值 kgCO2e/基准单位')),
                ('valid_from', models.DateField(verbose_name='生效日')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='失效日')),
                ('source', models.CharField(max_length=256, verbose_name='来源')),
                ('is_fictional', models.BooleanField(default=False, verbose_name='虚构示例因子')),
                ('notes', models.TextField(blank=True, verbose_name='用途与免责声明')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pcf.region', verbose_name='适用地区')),
            ],
            options={
                'verbose_name': '排放因子',
                'verbose_name_plural': '排放因子',
                'ordering': ['code', '-valid_from', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=128)),
                ('activity_type', models.CharField(choices=[('electricity', '电力'), ('fuel', '燃料'), ('auxiliary', '辅料')], max_length=16)),
                ('raw_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('raw_unit_code', models.CharField(max_length=16)),
                ('amount_in_base', models.DecimalField(decimal_places=6, max_digits=26)),
                ('factor_id', models.PositiveBigIntegerField()),
                ('factor_code', models.CharField(max_length=64)),
                ('factor_version', models.CharField(max_length=16)),
                ('factor_name', models.CharField(max_length=128)),
                ('factor_region_code', models.CharField(max_length=32)),
                ('factor_value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('factor_status_at_calc', models.CharField(max_length=16)),
                ('emissions_kg', models.DecimalField(decimal_places=6, max_digits=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pcf.report')),
            ],
            options={
                'verbose_name': '报告结果行',
                'verbose_name_plural': '报告结果行',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='方案名称')),
                ('product', models.CharField(max_length=128, verbose_name='产品名称')),
                ('functional_unit', models.CharField(default='1 件产品', max_length=64, verbose_name='功能单位')),
                ('boundary_note', models.CharField(default='门到门：原材料入厂 → 产品出厂', max_length=256, verbose_name='系统边界')),
                ('as_of', models.DateField(verbose_name='核算基准日（因子适用日）')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认')], default='draft', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='pcf.scenario', verbose_name='复制来源')),
            ],
            options={
                'verbose_name': '生产方案',
                'verbose_name_plural': '生产方案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='pcf.scenario'),
        ),
        migrations.CreateModel(
            name='UnaccountedLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=128)),
                ('activity_type', models.CharField(choices=[('electricity', '电力'), ('fuel', '燃料'), ('auxiliary', '辅料')], max_length=16)),
                ('raw_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('raw_unit_code', models.CharField(max_length=16)),
                ('requested_factor_code', models.CharField(blank=True, max_length=64)),
                ('reason_code', models.CharField(max_length=32)),
                ('reason_detail', models.CharField(max_length=256)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unaccounted', to='pcf.report')),
            ],
            options={
                'verbose_name': '未核算项',
                'verbose_name_plural': '未核算项',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('electricity', '电力'), ('fuel', '燃料'), ('auxiliary', '辅料')], max_length=16, verbose_name='活动类型')),
                ('name', models.CharField(max_length=128, verbose_name='活动名称')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='活动量')),
                ('factor_code', models.CharField(blank=True, max_length=64, verbose_name='导入时请求的因子编码')),
                ('external_ref', models.CharField(blank=True, max_length=128, verbose_name='外部单据号（防重复导入）')),
                ('factor_resolution_note', models.CharField(blank=True, max_length=256, verbose_name='因子解析说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pcf.emissionfactor', verbose_name='指定因子')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pcf.scenario')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pcf.unit', verbose_name='活动单位')),
            ],
            options={
                'verbose_name': '活动数据',
                'verbose_name_plural': '活动数据',
                'ordering': ['activity_type', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='emissionfactor',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='uq_factor_code_version'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref__gt', '')), fields=('scenario', 'external_ref'), name='uq_activity_external_ref'),
        ),
    ]
